language: python
python:
  - 2.7
  - 3.6
script: pytest
deploy:
  - provider: pypi
    user: awsgi-ci
    password: $PYPI_PASSWORD
    on:
      tags: true
    distributions: "sdist bdist_wheel"
    server: https://upload.pypi.org/legacy/
  - provider: pypi
    user: awsgi-ci
    password: $TESTPYPI_PASSWORD
    on:
      branch: pypi-test
    distributions: "sdist bdist_wheel"
    server: https://test.pypi.org/legacy/
